exclude: node_modules
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: detect-private-key
  - repo: local
    hooks:
      - id: setInternalDepsLocalSource
        name: setInternalDepsLocalSource
        entry: \./\.commitHooks/setInternalDepsLocalSource.zsh
        language: script
        stages: [post-commit, post-checkout]
        always_run: true
