exclude: node_modules
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: detect-private-key
  - repo: local
    hooks:
      - id: checkInternalDependencySources.zsh
        name: checkInternalDependencySources.zsh
        entry: \./\.commitHooks/checkInternalDependencySources.zsh
        files: package.json
        language: script
        stages: [pre-commit]
        always_run: true
      - id: avoidCommitIfNotTestRoot.zsh
        name: avoidCommitIfNotTestRoot.zsh
        entry: \./\.commitHooks/avoidCommitIfNotTestRoot.zsh
        files: package.json
        language: script
        stages: [pre-commit]
        always_run: true
