exclude: node_modules
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: detect-private-key
  - repo: local
    hooks:
      - id: setInternalDepsRemoteSource
        name: setInternalDepsRemoteSource
        entry: \./\.commitHooks/setInternalDepsRemoteSource.zsh
        files: package.json
        language: script
        stages: [pre-commit]
        always_run: true
      - id: setInternapDepsLocalSource
        name: setInternalDepsLocalSource
        entry: \./\.commitHooks/setInternalDepsLocalSource.zsh
        files: package.json
        language: script
        stages: [post-commit, post-checkout]
        always_run: true
